name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build and Run Test Docker image
      run: docker build -f ./client/Dockerfile.dev -t bevooh94/react-test ./client
    - name: Run test cases
      run: |
        docker run -e CI=true bevooh94/react-test npm test -- --coverage
    - name: Build other Docker images
      run: |
        docker build -f ./client/Dockerfile -t bevooh94/react-prod ./client
        docker build -f ./server/Dockerfile -t bevooh94/server-api ./server
        docker build -f ./worker/Dockerfile -t bevooh94/worker ./worker
    - name: Login to Docker Hub
    - uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_ID }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Upload Docker images to Docker hub
      run: |
        docker push bevooh94/react-prod
        docker push bevooh94/server-api
        docker push bevooh94/worker
    
      
      
      
